python -m application.tests.test_lstm_spell_classifier_w_context
python -m application.tests.test_lstm_spell_classifier_w_context_onehot
python -m application.tests.test_lstm_spell_classifier_wo_context